backend:
  name: github
  repo: https://github.com/Manoj-63/documentation
  base_url: https://us-central1-my-doc-ccb3a.cloudfunctions.net
  auth_endpoint: /oauth/auth

# publish_mode: editorial_workflow # works with GitHub repositories only

media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

slug:
  encoding: "unicode"
  clean_accents: true
  sanitize_replacement: "."

collections:
  - name: "help" # Used in routes, e.g., /admin/collections/blog
    label: "Help" # Used in the UI
    folder: "content/help" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}+{{language}}" # Filename template, !!! '+' will be replaced by '.'
    fields: # The fields for each document, usually in front matter
      - {label: "Language", name: "language", widget: "select", options: ["en", "fr", "es"]}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "select", options: ["Ajit", "Raksha", "Tarun", "Manoj"]}
      - {label: "Weight", name: "weight", widget: "number", valueType: "int"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "how-to" # Used in routes, e.g., /admin/collections/blog
    label: "How To" # Used in the UI
    folder: "content/how-to" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}+{{language}}" # Filename template, !!! '+' will be replaced by '.'
    fields: # The fields for each document, usually in front matter
      - {label: "Language", name: "language", widget: "select", options: ["en", "fr", "es"]}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "select", options: ["Ajit", "Raksha", "Tarun", "Manoj"]}
      - {label: "Weight", name: "weight", widget: "number", valueType: "int"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "faq" # Used in routes, e.g., /admin/collections/blog
    label: "FAQ" # Used in the UI
    folder: "content/faq" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}+{{language}}" # Filename template, !!! '+' will be replaced by '.'
    fields: # The fields for each document, usually in front matter
      - {label: "Language", name: "language", widget: "select", options: ["en", "fr", "es"]}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "select", options: ["Ajit", "Raksha", "Tarun", "Manoj"]}
      - {label: "Weight", name: "weight", widget: "number", valueType: "int"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}+{{language}}" # Filename template, !!! '+' will be replaced by '.'
    fields: # The fields for each document, usually in front matter
      - {label: "Language", name: "language", widget: "select", options: ["en", "fr", "es"]}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "select", options: ["Ajit", "Raksha", "Tarun", "Manoj"]}
      - {label: "Weight", name: "weight", widget: "number", valueType: "int"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "guides" # Used in routes, e.g., /admin/collections/blog
    label: "Guides" # Used in the UI
    folder: "content/guides" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}+{{language}}" # Filename template, !!! '+' will be replaced by '.'
    fields: # The fields for each document, usually in front matter
      - {label: "Language", name: "language", widget: "select", options: ["en", "fr", "es"]}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "select", options: ["Ajit", "Raksha", "Tarun", "Manoj"]}
      - {label: "Weight", name: "weight", widget: "number", valueType: "int"}
      - {label: "Body", name: "body", widget: "markdown"}
